title: Mr.Brown
description: Mr.Brown is a responsive jekyll theme
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
baseurl: "/web" # the subpath of your site, e.g. /blog

sass:
    sass_dir: _sass

# Comments
discus_identifier: mr-brown
txtpen_identifier: raizer85

# Social settings
facebook_url: https://www.facebook.com/juandavid.gomez.58
linkedin_url: https://www.linkedin.com/in/juan-david-gomez-escobar/
github_url: https://github.com/juan-david-gomez/
